site_name: MBI API DOCS
copyright: ⓒ MBI Solution inc. all rights reserved
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
    - icon: fontawesome/brands/happytalk
      link: https://happytalk.io
#  alternate:
#    - name: English(Not Support)
#      link: /en/
#      lang: en
#    - name: 한국어
#      link: /kr/
#      lang: kr
nav:
  - MBI API DOCS 소개 : index.md
  - Biz API :
    - 기본 정보 : Biz-API/index.md
    - 상담 :
      - 상담방 생성 : Biz-API/counsel/create_counseling.md
      - 상담 종료 : Biz-API/counsel/end_counseling.md
      - 메시지 발신 : Biz-API/counsel/send_message.md
      - 이전 상담사 연결 가능 여부 : Biz-API/counsel/check_previous_counselor.md
    - API 실패 코드 : Biz-API/reference_docs/api_fail_code.md
  - 해피톡 :
    - 기본 정보 : Happytalk/index.md
    - 고객 정보 수정:
      - 상담 내역 조회:
        - 고객 ID 검색: Happytalk/customer/counsel_detail_search/customer_id.md
        - 고객 UUID 검색: Happytalk/customer/counsel_detail_search/customer_uuid.md
        - 상담방 ID 검색: Happytalk/customer/counsel_detail_search/counsel_room_id.md
        - 상담방 목록 검색: Happytalk/customer/counsel_detail_search/counsel_room_list.md
      - 서비스 이용내역 조회: Happytalk/customer/service_usage_history.md
      - 고객 정보 수정: Happytalk/customer/customer_info_modify.md
    - 고급 설정 :
      - 인증 관리 :
        - 고객 정보 요청 연동 :
          - JTW(토큰) 발급 : Happytalk/advanced/authentication_management/customer_info_request/JWT_issuance.md
          - 인증 결과 메시지 : Happytalk/advanced/authentication_management/customer_info_request/authentication_result_message.md
    - 아카이브 :
      - 상담방 : Happytalk/archive/counsel_room_list/db_chat_list.md
      - 채팅 : Happytalk/archive/chat_room/db_chat.md
      - 채팅 전송 파일 : Happytalk/archive/send_chat_file/db_chat_file.md
  - 카카오 상담톡 웹훅 :
    - 채널 인증 토큰 요청 : kakaotalk_webhook/request_token.md
    - 발신 프로필 :
      - 조회 : kakaotalk_webhook/sender/search.md
      - 등록 : kakaotalk_webhook/sender/create.md
      - 수정 :
        - 1대1 채팅 활성화 : kakaotalk_webhook/sender/modify/chat_activate.md
        - 1대1 채팅 비활성화 : kakaotalk_webhook/sender/modify/chat_deactivate.md
        - 수신 도메인 등록 및 수정 : kakaotalk_webhook/sender/modify/send_domain_update.md
        - 수신 도메인 조회 : kakaotalk_webhook/sender/modify/send_domain.md
    - 상담 :
      - 버튼을 통한 상담 시작 : kakaotalk_webhook/counseling/start_from_button.md
      - 메시지 전송 : kakaotalk_webhook/counseling/send_chat.md
      - 상담방 종료 : kakaotalk_webhook/counseling/end_of_counseling.md
      - 사용자 차단 : kakaotalk_webhook/counseling/user_ban.md
      - 사용자 차단 해제 : kakaotalk_webhook/counseling/user_unban.md
    - 상담 정보 수신 :
      - 메타 정보 수신 : kakaotalk_webhook/counsel_data_reception/kakao_meta_data.md
      - 상담 메시지 수신 : kakaotalk_webhook/counsel_data_reception/chat_reception.md
      - 세션 종료 정보 수신 : kakaotalk_webhook/counsel_data_reception/session_end_data.md
    - 파일 업로드 :
      - 이미지 업로드 : kakaotalk_webhook/file_upload/img_upload.md
      - 파일 업로드 : kakaotalk_webhook/file_upload/file_upload.md
    - 참조 문서 :
        - 카테고리 문서 : kakaotalk_webhook/reference_docs/category.md
        - 카테고리 조회 API : kakaotalk_webhook/reference_docs/category_api.md
        - API 코드 정의 : kakaotalk_webhook/reference_docs/api_code_dict.md
theme:
  language: kr
  name: 'material'
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  custom_dir: overrides
  features:
    - toc.follow`
    - navigation.top
    - content.tabs.link
markdown_extensions:
  - meta
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true